### ISSUE TITLE
Identify gitlab instances by unique id

### ISSUE THREAD

**Issue by manuelstein** [immobiliare/backstage-plugin-gitlab#118]
Hello,

I've noticed the multiple GitLab instance support numbers instances as they appear in the GitLab integration config.
AFAIK, the processor runs on catalog entries once they are ingested, so when the GitLab integration array changes (e.g. a new GitLab instance is added), there would be a mismatch on catalog entries that were processed before the change.

I'm suggesting to identify the GitLab instance by a unique ID. I used to maintain an implementation based on the loblaw version that was using the GitLab instance's hostname (GitLab config `host` field). Btw, thanks for taking over and actively driving the development of this plugin.

I'm implementing my suggested change for our internal use and would happily contribute upstream.

wdyt?

**Comment by antoniomuso** [comment]
Hi @manuelstein, if you give the time to Backstage, it automatically reprocesses the entities with the correct instance annotation (I tested it, and it does it).  However, your proposal LGTM, so you are welcome if you want to implement it.
