### ISSUE TITLE
Should issues and MR id columns be the project-specific ones?

### ISSUE THREAD

**Issue by sichapman** [immobiliare/backstage-plugin-gitlab#150]
I noticed that on the issues and merge request tables, the ID column appears to be the global ID instead of the project-specific one shown to end users ie. what appears in the UI.  Since this is a column in a table that users may refer to, it seems more sensible to use the latter (which I think the GItlab API refer to as `iid`)

**Comment by antoniomuso** [comment]
Hi @sichapman thanks for the report.
