### ISSUE TITLE
Add card to handle CODEOWNERS standard

### ISSUE THREAD

**Issue by antoniomuso** [immobiliare/backstage-plugin-gitlab#16]
We can add a card to handle CODEOWNER standard using gitlab API.

The possible gitlab API can be: `api/v4/projects/:id/repository/files/CODEOWNERS?ref=master`

**Comment by snips-dev** [comment]
# Proposal

As showed below we can add the owners info directly in the contributor card renaming it *People*

![People Card Gitlab Plugin](https://user-images.githubusercontent.com/68282513/208876747-f2671b9f-cb71-48fb-a410-272f4eccbff3.png)
