### ISSUE TITLE
Remove bots from contributors card.

### ISSUE THREAD

**Issue by antoniomuso** [immobiliare/backstage-plugin-gitlab#18]
What do you think of removing bots from contributors' cards?

**Comment by Parsifal-M** [comment]
Would love to help on this one and give back to the community, do you have an idea on how we can achieve this?

Thanks!

**Comment by antoniomuso** [comment]
Hi @Parsifal-M, you can achieve the feature by reading the docs of https://docs.gitlab.com/ee/api/users.html and adding the rights parameters to the API `/users` call.

**Comment by Parsifal-M** [comment]
I will pick this up over the weekend, I already see what you mean.

Thanks!

**Comment by Parsifal-M** [comment]
Hey! 👋 

I forgot to link this to #94 😅
