### ISSUE TITLE
integration of self hosted gitlab not working

### ISSUE THREAD

**Issue by Santonian** [immobiliare/backstage-plugin-gitlab#236]
we have self hosted gitlab and I setup the integration like so:

integrations:
  gitlab:
    - host: gitlab.xxxxx.de
      token: MY-TOKEN
      apiBaseUrl: https://gitlab.xxxxx.de/api/v4
      baseUrl: http://gitlab.xxxxx.de

The basic backstage installation cann work with this and can read catalog files from my gitlab repositories. 

But the gitlab plugin gives me all kind of 404, when I try to open the gitlab tab of an entity:

`
...
1] 2023-06-06T08:27:11.419Z backstage info ::ffff:127.0.0.1 - - [06/Jun/2023:08:27:11 +0000] "GET /api/gitlab/gitlab.com/projects/1415/languages? HTTP/1.1" 404 35 "http://localhost:3000/" "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/112.0" type=incomingRequest
[1] 2023-06-06T08:27:11.445Z backstage info ::ffff:127.0.0.1 - - [06/Jun/2023:08:27:11 +0000] "GET /api/gitlab/gitlab.com/projects/1415/merge_requests? HTTP/1.1" 404 35 "http://localhost:3000/" "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/112.0" type=incomingRequest
[1] 2023-06-06T08:27:11.468Z backstage info ::ffff:127.0.0.1 - - [06/Jun/2023:08:27:11 +0000] "GET /api/gitlab/gitlab.com/projects/1415? HTTP/1.1" 404 35 "http://localhost:3000/" "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/112.0" type=incomingRequest
[1] 2023-06-06T08:27:11.668Z backstage info ::ffff:127.0.0.1 - - [06/Jun/2023:08:27:11 +0000] "GET /api/gitlab/gitlab.com/projects/1415? HTTP/1.1" 404 35 "http://localhost:3000/" "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/112.0" type=incomingRequest
[1] 2023-06-06T08:27:11.674Z backstage info ::ffff:127.0.0.1 - - [06/Jun/2023:08:27:11 +0000] "GET /api/gitlab/gitlab.com/projects/1415/repository/contributors?sort=desc HTTP/1.1" 404 35 "http://localhost:3000/" "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/112.0" type=incomingRequest
[1] 2023-06-06T08:27:11.679Z backstage info ::ffff:127.0.0.1 - - [06/Jun/2023:08:27:11 +0000] "GET /api/gitlab/gitlab.com/projects/1415? HTTP/1.1" 404 35 "http://localhost:3000/" "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/112.0" type=incomingRequest
[
...
`

did I miss something or is the plugin not working with self hosted gitlab installations?

**Comment by mscam** [comment]
same issue here. I followed the migration guide step by step 🤔

**Comment by rolandsgs** [comment]
It looks like that is trying to connect to gitlab.com and not to gitlab.xxxx.de. Did you set the gitlab provider under catalog  with host value with the same value in host at integrations? 

[Gitlab Discovery](https://backstage.io/docs/integrations/gitlab/discovery)

**Comment by antoniomuso** [comment]
The plugin works with custom gitlab plugin. But it seems that you are not using the processor or that processor is now working correctly.

**Comment by mscam** [comment]
@antoniomuso sure, I will post the value that later today 👍 btw, I have followed section 5 of README.md

**Comment by Santonian** [comment]
Ok, this is strange, after removing "integrations.gitlab.baseUrl" from the app-config.yaml it is working. after adding it again, it stops working again.

I don't see why there is a relationship between these two things.. anyway, just glad that it's finally working.

**Comment by antoniomuso** [comment]
> Ok, this is strange, after removing "integrations.gitlab.baseUrl" from the app-config.yaml it is working. after adding it again, it stops working again.
> 
> I don't see why there is a relationship between these two things.. anyway, just glad that it's finally working.

Now I am seeing that you have put HTTP for `baseUrl` and HTTPS for `apiBaseUrl` is this right?

**Comment by mscam** [comment]
value of` gitlab.com/instance` was not found in my case, that's probably it was not working

**Comment by antoniomuso** [comment]
Can you post your configurations? The processor adds the instance base on `backstage.io/source-location` What kind of source location do you have?

**Comment by mscam** [comment]
I can't post the configurations right now but they are almost the same as described by @Santonian . the source location has catalog-info.yaml files that already have gitlab annotation `gitlab.com/project-id`. adding `gitlab.com/instance: 'gitlab.hostname.xyz'`to the catalog files made the plugin working.

**Comment by antoniomuso** [comment]
What kind of entity are you using?

**Comment by ccarbonellbh** [comment]
I am having a similar issue and had to add `gitlab.com/instance` and `gitlab.com/project-id` to annotations for my component. Doing that gets me further along the loading process, but now I get 401s, despite the fact that I'm logging into backstage with gitlab as the auth provider (with no issues). The url it's hitting where I get the 401 is http://localhost:7007/api/gitlab/{our.gitlab.instance}/projects/{project_id}?. I see the token in the Authorization header but it's always invalid according to the response

**Comment by kjenney** [comment]
I have similar issues. I just installed and configured the plugin today with the latest README. There is no mention of `apiBaseUrl` in the README, but it is required - at least for self-hosted instances. 

WIthout it everything crashes with:

```
Backend failed to start up Error: Invalid Gitlab integration config, 'undefined' is not a valid apiBaseUrl
```

I'm getting a bunch of `wrong project_slug or project_id` errors in the GitLab tab. I've verified that my personal access token does work and that the project_id is correct - both using curl:

```
curl --header 'PRIVATE-TOKEN: redacted' https://gitlab.private.io/api/v4/projects/2/
``` 

I followed all of the required steps - none of the optional steps.

**Comment by kjenney** [comment]
I ended up resolving my issue by adding the `gitlab.com/instance: gitlab.private.io` annotation. The README lists this as an `or` but apparently it is not. 

Thanks everybody who works on this project!!

**Comment by kjenney** [comment]
Created PR - https://github.com/immobiliare/backstage-plugin-gitlab/pull/319 to update the README.

**Comment by antoniomuso** [comment]
This is not the right solution, the code should automatically build the `gitlab.com/instance` annotation

**Comment by kjenney** [comment]
In your opinion this is not the right solution? If you have multiple instances you'd have to differentiate them.

**Comment by kjenney** [comment]
If this is a better solution to automatically annotating based on instances set in configuration, please explain how this is done. It is not apparent by reading through the README.

**Comment by antoniomuso** [comment]
The Gitlab Filler Processor does the auto-annotation. If you want to integrate it, follow point .5 of the `Setup`:
```
5. Add the GitLab Filler Processor, this allows auto-filling of the annotations like the project ID and slug:
