### ISSUE TITLE
Handle missing of CODEOWNERS file 

### ISSUE THREAD

**Issue by antoniomuso** [immobiliare/backstage-plugin-gitlab#26]
For now, if the CODEOWNERS file is missing, we show the card with the code owners section but without owners. 
I think in that case, we can remove the "owners" section, WDYT?

**Comment by JellyBellyDev** [comment]
absolutely! 😉

**Comment by antoniomuso** [comment]
@snips-dev , can you take care of it?

**Comment by snips-dev** [comment]
👍

**Comment by antoniomuso** [comment]
Thank you!
