### ISSUE TITLE
Using the plugin in an environment with a basePath doesn't work

### ISSUE THREAD

**Issue by gabrielhuber** [immobiliare/backstage-plugin-gitlab#263]
Using the plugin in an environment with a baseUrl seems not to work. I tried to deploy the plugin to a backstage installation with for example this baseUrl: https://mykuberneteshost.de/subpath/backstage/... using a selfhosted gitlab installation with this url: https://mygitlabinstallation.de/

On startup the plugin creates a Proxy rewrite rule with this log message: Proxy rewrite rule created "^/subpath/backstage/api/gitlab/mygitlabinstallation.de/" ->"/api/v4"

But this Proxy rewrite rule seems to be wrong. When I try to open https://mykuberneteshost.de/subpath/backstage/api/gitlab/mygitlabinstallation.de/projects/my-group%2Fmyproject the redirect tries to open https://mygitlabinstallation.de/... instead of https://mygitlabinstallation.de/api/v4/...

I found a solution that worked for me, but I'm not sure if it is correct in any case. I copied the source code an rewrote the file https://github.com/immobiliare/backstage-plugin-gitlab/blob/main/packages/gitlab-backend/src/service/router.ts.
There I removed the ${basePath} from the pathRewrite. Line 61 and 63:
                pathRewrite: {
                    [`^/api/gitlab/${host}`]: apiUrl.pathname,
                },
instead of:
                pathRewrite: {
                    [`^${basePath}/api/gitlab/${host}`]: apiUrl.pathname,
                },

**Comment by antoniomuso** [comment]
Have you defined `integrations.gitlab[0].apiBaseUrl` variable in `app-config.yaml`?

**Comment by gabrielhuber** [comment]
My configuration look like that:
app-config.yaml:

...
backend:
  baseUrl: https://https://mykuberneteshost.de/subpath/backstage
  ...
  
integrations:
  gitlab:
    - host: mygitlabinstallation.de
      token: ${GITLAB_TOKEN}
      apiBaseUrl: https://mygitlabinstallation.de/api/v4/
      baseUrl: https://gitlab.idst.ibaintern.de/
...

**Comment by antoniomuso** [comment]
`basePath` seems wrong formatted
