### ISSUE TITLE
Add request caching with low TTL 

### ISSUE THREAD

**Issue by antoniomuso** [immobiliare/backstage-plugin-gitlab#32]
We can add request caching with a lower TTL to reduce the number of duplicated requests.

This should also be done by caching the stale responses.

**Comment by JellyBellyDev** [comment]
Good, but I think this has higher priority #7, no?

**Comment by antoniomuso** [comment]
Yes, it has, but #7 is the more complicated feature because it depends on #8 , And to do this, we have to create a backend part of this plugin with a Processor. The Processor should enrich the component with the GitLab `project-id.`

**Comment by JellyBellyDev** [comment]
@antoniomuso all clear, thank you

**Comment by simonecorsi** [comment]
This could benefit from an LRU cache instead of a fixed for all TTL!

**Comment by antoniomuso** [comment]
I am just thinking of simply changing the cache policy of `fetch` https://developer.mozilla.org/en-US/docs/Web/API/Request/cache#value

**Comment by Parsifal-M** [comment]
> I am just thinking of simply changing the cache policy of `fetch` https://developer.mozilla.org/en-US/docs/Web/API/Request/cache#value

Which did you have in mind? Could possibly help out with this 👍

**Comment by antoniomuso** [comment]
Now that we have the backend part, we can handle caching from the server side. This can be done by changing the `cache-control` header with TTL equal to 0 with a TTL of 10 seconds.
