### ISSUE TITLE
Use GitLab auth to render info

### ISSUE THREAD

**Issue by pleroux-bell** [immobiliare/backstage-plugin-gitlab#321]
Hi,

I was wondering if there was a way to use the signed in users GitLab authentication to render the GitLab cards to limit what can be viewed and not leak commits or other information that the user wouldn't have visibility in GitLab.

Thanks

**Comment by antoniomuso** [comment]
Hi @pleroux-bell, unfortunately, the feature you are looking for is not available at the moment.
