### ISSUE TITLE
Gitlab hosted 404 error, wrong project_slug or project_id, with GitlabFillerProcessor configured.

### ISSUE THREAD

**Issue by JWWilks** [immobiliare/backstage-plugin-gitlab#402]
After following the integration steps, including GitlabFillerProcessor, I can see 404 errors in the network tab where the gitlab components are trying to reach an endpoint in the backend.

❌  `http://localhost:7007/api/gitlab/rest/0/projects/{ORGANIZATION}%2F{GROUP}%2F{SUBGROUP}%2F{SUBGROUP}%2F{REPOSITORY}?`

 I notice that when I make a call without "rest" in the endpoint, I get a valid response with correct data.
✅ `http://localhost:7007/api/gitlab/0/projects/{ORGANIZATION}%2F{GROUP}%2F{SUBGROUP}%2F{SUBGROUP}%2F{REPOSITORY}?`

I'm running into this issue after upgrading backstage from v1.16.0 -> v1.23.0 - but I removed the gitlab plugin before upgrading and am now struggling to add it back. I have read your [migration guide](https://github.com/immobiliare/backstage-plugin-gitlab/blob/main/docs/migration-guides.md), but I was never on v2 in the first place.

My gitlab config is basic:
```yaml
integrations:
  gitlab:
    - host: gitlab.com
      token: ${GITLAB_TOKEN}
 ```
- No proxy is configured.
- The issue is the same if I configure `apiBaseUrl: https://gitlab.com/api/v4/`
- Gitlab Org Discovery and Gitlab Entity Discovery are working fine with the same gitlab token.
- The issue is present on entities of `Component` kind, but I have tried adding `allowedKinds: ['Component']` explicitly.

**Comment by antoniomuso** [comment]
Have you installed the latest version of the plugin?
