### ISSUE TITLE
Showing Tags

### ISSUE THREAD

**Issue by javedfaruquee1** [immobiliare/backstage-plugin-gitlab#403]
Can you add config details on to fetch tag from gitlab to show on backstage??

**Comment by antoniomuso** [comment]
hi @javedfaruquee1, Can you explain better what you mean?

**Comment by javedfaruquee1** [comment]
![tempsnip](https://github.com/immobiliare/backstage-plugin-gitlab/assets/127127240/309773e1-2c22-4937-8057-cad7ca7d617c)

Can we add another dialog similar to attached Merge request for Displaying details for Tags as well, displaying
associated details for the tag like:

name of tag, 
commit.short_id,
commit.title, 
commit.message,
commit.author_name,
commit.committed_date

**Comment by javedfaruquee1** [comment]
Hi, Another question can is support multiple token for different gitlab subgroups or Projects?

**Comment by antoniomuso** [comment]
> Hi, Another question can is support multiple token for different gitlab subgroups or Projects?

hi @javedfaruquee1, sorry for the late response. This kind of feature is difficult to think of in a good way without reducing the Developer experience.  The new release [6.5.0](https://github.com/immobiliare/backstage-plugin-gitlab/releases/tag/v6.5.0) supports OIDC authorization. I believe this can resolve your problem.
