### ISSUE TITLE
Unable to register an existing component.

### ISSUE THREAD

**Issue by djh2020** [immobiliare/backstage-plugin-gitlab#41]
I am kicking the tires using a local backstage build.  I am trying to get a gitlab integration working but I am unable to register an existing component.  Can someone give me some tips for debugging this?  I am using 

"@immobiliarelabs/backstage-plugin-gitlab": "^2.1.0"

{"error":{"name":"InputError","message":"Error: Unable to read url, Error: Could not get GitLab project ID for: https://gitlab.com/...../blob/main/catalog-info.yaml, Error: GitLab Error 'undefined', undefined","stack":"InputError: Error: Unable to read url, Error: Could not get GitLab project ID for:

appreciate any insights / tips

**Comment by antoniomuso** [comment]
Hi @djh2020, this seems to be a bug with the official Backstage integration with GitLab https://github.com/backstage/backstage/issues/11874 , this plugin does not handle the registration of components.
