### ISSUE TITLE
CODEOWNERS not shown

### ISSUE THREAD

**Issue by matteosilv** [immobiliare/backstage-plugin-gitlab#43]
If I have CODEOWNERS in the default path, shouldn't I be able to see them? They are not shown. It's worth to specify my codeowners file has only one group and not single individuals

**Comment by antoniomuso** [comment]
Hi @matteosilv, thanks for reporting. This is a bug; we will resolve it as soon as possible.

**Comment by snips-dev** [comment]
Hi @matteosilv,
is the "Owners" Label shown correctly in the Card and is just missing the avatars? or the label doesn't appear at all?
This info should help me investigate!

**Comment by matteosilv** [comment]
The label doesn't appear at all

**Comment by antoniomuso** [comment]
Hi @matteosilv, this fix is available with the new release [v3.0.0](https://github.com/immobiliare/backstage-plugin-gitlab/releases/tag/v3.0.0).
This release adds auto-filling of the annotations and the support of multi-gitlab instances.
