### ISSUE TITLE
OIDC login possible?

### ISSUE THREAD

**Issue by elaine-mattos** [immobiliare/backstage-plugin-gitlab#432]
Hi,

currently the plugin uses the integration token to access GitLab. Would it be possible to implement another login mechanism, such as OIDC? This would ensure that GitLab access is restricted to the logged-in user rather than a technical user account.

thanks for the awesome plugin!

**Comment by antoniomuso** [comment]
Hi @elaine-mattos, Yes, it would. I will plan to do it.

**Comment by antoniomuso** [comment]
Hi @elaine-mattos, now this feature is up on https://github.com/immobiliare/backstage-plugin-gitlab/releases/tag/v6.5.0

**Comment by elaine-mattos** [comment]
Thanks a LOT @antoniomuso!
