### ISSUE TITLE
Gitlab MR request by Owner card

### ISSUE THREAD

**Issue by nia-potato** [immobiliare/backstage-plugin-gitlab#476]
Hi, thanks for the great plugin,

I was wondering if it would be easy to add a additional card that could be the gitlab version of [github pull requests card](https://www.npmjs.com/package/@roadiehq/backstage-plugin-github-pull-requests) for users to view their assigned the MRs in the home page or overview tab?

**Comment by antoniomuso** [comment]
> Hi, thanks for the great plugin,
> 
> I was wondering if it would be easy to add a additional card that could be the gitlab version of [github pull requests card](https://www.npmjs.com/package/@roadiehq/backstage-plugin-github-pull-requests) for users to view their assigned the MRs in the home page or overview tab?

Hi @nia-potato, 
I apologize for the delayed response; I missed the issue. It is a great feature, and I will schedule it for the next version.
If you have the time and would like to, your help in working on the feature would be greatly appreciated.

**Comment by nia-potato** [comment]
hi @antoniomuso Thanks for the response. 

I cant make any promises, but il let you know in this thread if i have the time, thanks for your consideration on developing this  for the next version tho!

**Comment by nia-potato** [comment]
note stale

**Comment by nia-potato** [comment]
hi @antoniomuso  just sent in a PR please take a look. 

Few Issues with the current setup: 
- i do have a internal version of this working with hardcoded gitlab instance values that are specific to our us working locally. since the `gitlabInstance()` is fetched from entity, i could not have re-used that value. it should rather be a independent variable fetched from the app-config that is not entity related. 
- The added MR board will add a small jira icon if it detects a JIRA ticket within the title, then based on the existing hardcoded jiraInstance value it will redirect the user to their jira ticket. If there is no Jira Issue detected in the title, there are no icon shown within the MR board. This issue once again i would need your recommendation on how we should fetch the jiraInstance to make use of this feature, it has been pretty useful internally already. 

- This last issue I particularly need to you shed some light for me: our current version of MR Assigned and requested Review card are fetching MRs totally fine locally, but when deployed on our production instance, it is then showing no MRs requested. 

the difference between the production instance vs my local test instance is that the production instance uses a admin PAT where my local dev is using a personal PAT, however as you can see from the API methods, we are first resolving the backstage user ID then crafting the API call to gitlab. and i can verify the api path is the same for both the server and local side. Do you have any ideas on this?
