### ISSUE TITLE
bug: README Relative Links

### ISSUE THREAD

**Issue by JWWilks** [immobiliare/backstage-plugin-gitlab#524]
In the embedded README, relative links are not parsed, so take you to the page relative to the backstage instance. To fix this we should parse the response from the README and convert links like `docs/abcd.md` , `myfile.abc` , `./docs/abcd.md`, `./folder/subfolder/../file.md` using the gitlab host + slug.

Happy to contribute when I get the chance.

**Comment by JellyBellyDev** [comment]
Thanks for reporting @JWWilks and any contribution is welcome! 😎

**Comment by antoniomuso** [comment]
Good catch @JWWilks, we can use something like: `${projectDetails.web_url}/-/blob/${projectDetails.default_branch}/${relativePath}`, the relative path should be evaluated considering the location of README.
