### ISSUE TITLE
Too many loading indicator is visible

### ISSUE THREAD

**Issue by krisztianmiko** [immobiliare/backstage-plugin-gitlab#550]
Hello!

Many loading indicators are visible when the User clicks on the project GitLab page.
I know it's necessary to see any actions on the page, but as you see on the attached screenshot it's too much at first.

By the way, I expected that when I refresh the page or just visit again the Gitlab page, then there should be a cache, but it always reloads, and see the loading indicators again.

<img width="1330" alt="Many loadin indicators on Gitlab tab" src="https://github.com/user-attachments/assets/57d6292f-2f61-4eaa-b507-acad09e64ced">

Do you have any solution to this?
Thanks!

**Comment by antoniomuso** [comment]
Hi @krisztianmiko, You are right. We have an issue tracking it at #32, but a stale bot has closed it. I reopened it.
