### ISSUE TITLE
Username regex blocking Code Owners from showing

### ISSUE THREAD

**Issue by darylgraham** [immobiliare/backstage-plugin-gitlab#558]
The Code Owners section of the People card does not show, and the console shows the following error:

`failed to load codeowners Error: @graham.daryl is not a valid owner name in rule * @user.name` 

The regex used to validate usernames here does not appear to allow periods in the username: https://github.com/immobiliare/backstage-plugin-gitlab/blob/main/packages/gitlab/src/components/utils.tsx#L116

The Gitlab documentation says they are an allowed character: https://docs.gitlab.com/ee/user/profile/

Going by the naming rules (which also say usernames cannot start with `_-.`), maybe the first capture group should look something like this?

```diff
- (^@[a-zA-Z0-9_\-/]*$)
+ (^@[a-zA-Z0-9][a-zA-Z0-9_\-/\.]*$)
```

**Comment by antoniomuso** [comment]
Hi @darylgraham, Thank you for the issue. You are right!
We can simplify all the regex in something like:
```regex
^@[a-zA-Z0-9][a-zA-Z0-9_\-\.]*([a-zA-Z0-9_\-]|[a-zA-Z0-9_])$
```
following the official regex: https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/path_regex.rb#L137
