### ISSUE TITLE
New backend system

### ISSUE THREAD

**Issue by ccapeng** [immobiliare/backstage-plugin-gitlab#561]
I am new in backstage.

I try to narrow down my issue of
GET /api/gitlab/rest/(my domain)/projects/(id) HTTP 1.1 400 ….. issue.

I have new backend system, do I still need to add plugins/catalog.ts, gitlab.ts like Setup Backend Plugin in readme?
Or, I just only need to follow Register To The New Backend System?

**Comment by ccapeng** [comment]
Also in readme “Old/New Gitlab Versions”, dose this mean for all gitlab versions?

In the api.ts, line 2&4 both import CustomGitlabCIClient.

Also in setupApi(), that is to pass APIOptions with 6 objects. I am looking version 6.6.0.

**Comment by antoniomuso** [comment]
No you only need to set up https://github.com/immobiliare/backstage-plugin-gitlab?tab=readme-ov-file#register-to-the-new-backend-system with the new backend system. Can you post the body output of the request from the browser?

**Comment by ccapeng** [comment]
Hi @antoniomuso, I actually did not have apis.ts implemented early on.
In order to pass ts checking, I do like
```
createApiFactory({
  api: GitlabCIApiRef,
  deps: ...
  factory: ({configApi, discoveryApi}) => {
    return CustomGitlabCIClient.setupAPI({
      gitlabAuthApi: {} as OauthApi,
      identitiApi: {} as IdentityApi,
      useOauth: false,
      discoveryApi,
      ...
    )}
  },
)}
```

So, in the web browser, I have "this.identityApi.getCretentials is not a function".
How do I implement `gitLabAuthApi` and `identityApi` in here?
I have @immobiliarelabs/backstage-plugin-gitlab 6.6.0.
Or, do I use other version that match the sample in the README.

**Comment by antoniomuso** [comment]
you have to add them in deps, then you will have in the OAUthApi and IdentityApi parameters. Follow  https://github.com/immobiliare/backstage-plugin-gitlab/blob/main/packages/gitlab/src/plugin.ts#L21

**Comment by ccapeng** [comment]
@antoniomuso Thanks. I got it work.
