### ISSUE TITLE
Parsing CODEOWNERS file fails if (period) . is in the name/group

### ISSUE THREAD

**Issue by mbilling** [immobiliare/backstage-plugin-gitlab#595]
**Repro**
1. Have a CODEOWNERS file with content (see below) in you repo where you have a catalog-info.yaml entity
2. Have a EntityPage.tsx page using <EntityGitlabPeopleCard />
3. Browse to the entity in backstage
4. You get following error message:
    **@my.full.name is not a valid owner name in rule * @my.full.name**

**CODEOWNERS** file content
```
* @my.full.name
```

**Reason**
The regex parsing the usern/group names in the CODEOWNERS file are very strict. I don't think this is necessary at all.
I doesn't matter what characters is used other than @ and [SPACE} (at least in the comtext of this plugin)

**PR Proposal**
[Parse with a much simpler regex](https://github.com/immobiliare/backstage-plugin-gitlab/blob/15965bb87196417cfa9d7f93ee00eb4299b5d064/packages/gitlab/src/components/utils.tsx#L115)
And include **.** as allowed
E.g.
^@([a-zA-Z0-9_\-\/<\.]+)(\s@([a-zA-Z0-9_\-\/\.]+))*$

**Comment by antoniomuso** [comment]
https://github.com/immobiliare/backstage-plugin-gitlab/pull/597

**Comment by mbilling** [comment]
Great, thanks for the fix
Much appreciated!
