### ISSUE TITLE
Plugin security

### ISSUE THREAD

**Issue by matteosilv** [immobiliare/backstage-plugin-gitlab#62]
Current configuration of the plugin requires a token with scope read_api to access all resources. However by using /gitlab-ci proxy any user logged into backstage can use gitlab apis. e.g.:

    https://my.backstage.com/api/proxy/gitlabci/projects
    
The user is able to list all projects with the token permissions.

Isn't it too permissive?

Is there a way to restrict the calls only to server side?

**Comment by antoniomuso** [comment]
Hi @matteosilv, yes, this is a problem. In fact, with the new [plugin version](https://github.com/immobiliare/backstage-plugin-gitlab/releases/tag/v3.0.0), we removed the proxy in favor of a custom backend, and now that we have it, we can think about reducing permissions.

**Comment by matteosilv** [comment]
Great stuff guys! Happy to help in the future!

**Comment by antoniomuso** [comment]
Thank you; your contribution is welcome :smiley:
